# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=500)),
                ('movie_url', models.CharField(max_length=1000)),
                ('movie_state', models.CharField(max_length=50)),
                ('movie_update', models.CharField(max_length=50)),
                ('movie_return', models.CharField(max_length=50)),
                ('movie_countdown', models.CharField(max_length=50)),
            ],
        ),
    ]
